---
name: grcov express
description: |
  Faster grcov github action that runs it from a container.
  Useful to gather rust test coverage data.
branding:
  icon: play-circle
  color: black
outputs:
  report:
    description: Absolute path to the generated code coverage file
runs:
  using: 'docker'
  image: 'Dockerfile'
