#!/bin/bash
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

OUTPUT_PATH=lcov.info

set -e -x

grcov . \
      -s . \
      --ignore "/*" --ignore "../*" \
      -o "$OUTPUT_PATH"
echo "::set-output name=report::$OUTPUT_PATH"

